// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportCollection(arg1) {
  return window['go']['importpkg']['Service']['ImportCollection'](arg1);
}

export function Startup(arg1) {
  return window['go']['importpkg']['Service']['Startup'](arg1);
}

export function SupportedSources() {
  return window['go']['importpkg']['Service']['SupportedSources']();
}
