// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {context} from '../models';

export function ImportCollection(arg1:api.ImportCollectionInput):Promise<api.ImportCollectionResult>;

export function Startup(arg1:context.Context):Promise<void>;

export function SupportedSources():Promise<Array<string>>;
