// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['collections']['Service']['Close']();
}

export function CreateCollection(arg1) {
  return window['go']['collections']['Service']['CreateCollection'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['collections']['Service']['CreateFolder'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['collections']['Service']['DeleteCollection'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['collections']['Service']['DeleteFolder'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['collections']['Service']['DeleteRequest'](arg1);
}

export function DuplicateRequest(arg1) {
  return window['go']['collections']['Service']['DuplicateRequest'](arg1);
}

export function LoadAllCollections() {
  return window['go']['collections']['Service']['LoadAllCollections']();
}

export function MoveFolder(arg1) {
  return window['go']['collections']['Service']['MoveFolder'](arg1);
}

export function MoveRequest(arg1) {
  return window['go']['collections']['Service']['MoveRequest'](arg1);
}

export function RenameCollection(arg1) {
  return window['go']['collections']['Service']['RenameCollection'](arg1);
}

export function RenameFolder(arg1) {
  return window['go']['collections']['Service']['RenameFolder'](arg1);
}

export function RenameRequest(arg1) {
  return window['go']['collections']['Service']['RenameRequest'](arg1);
}

export function ReorderRequests(arg1) {
  return window['go']['collections']['Service']['ReorderRequests'](arg1);
}

export function SaveRequest(arg1) {
  return window['go']['collections']['Service']['SaveRequest'](arg1);
}

export function Startup(arg1) {
  return window['go']['collections']['Service']['Startup'](arg1);
}
