// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['httpservice']['HTTPService']['Close']();
}

export function LoadWorkspaceState() {
  return window['go']['httpservice']['HTTPService']['LoadWorkspaceState']();
}

export function SaveWorkspaceState(arg1) {
  return window['go']['httpservice']['HTTPService']['SaveWorkspaceState'](arg1);
}

export function SendHttpRequest(arg1) {
  return window['go']['httpservice']['HTTPService']['SendHttpRequest'](arg1);
}

export function Startup(arg1) {
  return window['go']['httpservice']['HTTPService']['Startup'](arg1);
}
