// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunScript(arg1) {
  return window['go']['scripting']['Service']['RunScript'](arg1);
}
