// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scripting} from '../models';

export function RunScript(arg1:scripting.ScriptContext):Promise<scripting.ScriptResult>;
