// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['sse']['Service']['Close']();
}

export function Connect(arg1) {
  return window['go']['sse']['Service']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['sse']['Service']['Disconnect'](arg1);
}

export function Startup(arg1) {
  return window['go']['sse']['Service']['Startup'](arg1);
}
