// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function Connect(arg1:api.SseConnectPayload):Promise<api.SseConnectResult>;

export function Disconnect(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
