// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function Connect(arg1:api.WsConnectPayload):Promise<api.WsConnectResult>;

export function Disconnect(arg1:string):Promise<void>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function SendMessage(arg1:api.WsSendPayload):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
