// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['websocket']['Service']['Close']();
}

export function Connect(arg1) {
  return window['go']['websocket']['Service']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['websocket']['Service']['Disconnect'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['websocket']['Service']['ReadFileBase64'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['websocket']['Service']['SendMessage'](arg1);
}

export function Startup(arg1) {
  return window['go']['websocket']['Service']['Startup'](arg1);
}
