// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {context} from '../models';

export function SendHttpRequest(arg1:api.HttpRequestPayload):Promise<api.HttpResponsePayload>;

export function Startup(arg1:context.Context):Promise<void>;
