// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendHttpRequest(arg1) {
  return window['go']['httpclient']['HTTPService']['SendHttpRequest'](arg1);
}

export function Startup(arg1) {
  return window['go']['httpclient']['HTTPService']['Startup'](arg1);
}
